# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ "${modulesPath}/hardware/network/broadcom-43xx.nix"
      "${modulesPath}/installer/scan/not-detected.nix"
    ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "ahci" "usbhid"
    "usb_storage" "sd_mod"
  ];

  boot.kernelModules = [ "kvm-intel" ];
  #boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f7699781-5ab7-4850-849f-6f2d51fcbe54";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/8d616434-7e2a-4003-a775-2f01e69599c9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/67E3-17ED";
      fsType = "vfat";
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/220fcf44-9833-4408-b01e-55e5be903107";
     fsType = "ext4";
    };

  swapDevices = [
    # { device = "/dev/disk/by-uuid/a7a1aa67-8b24-4187-b69a-9c1702e084d7";
    # }
  ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = "performance";
}
