# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, modulesPath, lib, pkgs, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [ "virtio_pci" "ahci" "sd_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "console=ttyS0,19200n8" ];
  boot.loader.grub.extraConfig = ''
    serial --speed=19200 --unit=0 --word=8 --parity=no --stop=1;
    terminal_input serial;
    terminal_output serial
  '';

  fileSystems = {
    "/" =
      { device = "/dev/sda";
        fsType = "ext4";
      };
#    "/data" =
#      { device = "/dev/sdc";
#        fsType = "ext4";
#      };
  };

  swapDevices =
    [ { device = "/dev/sdb"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
}
